#############################################################################
# Makefile for building: Application
# Generated by qmake (3.1) (Qt 5.12.10)
# Project:  Application.pro
# Template: subdirs
# Command: D:\Software\Qt\5.12.10\mingw73_64\bin\qmake.exe -o Makefile Application.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = D:\Software\Qt\5.12.10\mingw73_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = D:\Software\Qt\5.12.10\mingw73_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = D:\Software\Qt\5.12.10\mingw73_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-Framework \
		sub-app


sub-Framework-qmake_all:  FORCE
	@if not exist Framework\ mkdir Framework\ & if not exist Framework\ exit 1
	cd Framework\ && $(QMAKE) -o Makefile C:\Users\ZZC\Desktop\Application\Framework\Framework.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd Framework\ && $(MAKE) -f Makefile qmake_all
sub-Framework: FORCE
	@if not exist Framework\ mkdir Framework\ & if not exist Framework\ exit 1
	cd Framework\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\ZZC\Desktop\Application\Framework\Framework.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-Framework-make_first: FORCE
	@if not exist Framework\ mkdir Framework\ & if not exist Framework\ exit 1
	cd Framework\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\ZZC\Desktop\Application\Framework\Framework.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-Framework-all: FORCE
	@if not exist Framework\ mkdir Framework\ & if not exist Framework\ exit 1
	cd Framework\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\ZZC\Desktop\Application\Framework\Framework.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-Framework-clean: FORCE
	@if not exist Framework\ mkdir Framework\ & if not exist Framework\ exit 1
	cd Framework\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\ZZC\Desktop\Application\Framework\Framework.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-Framework-distclean: FORCE
	@if not exist Framework\ mkdir Framework\ & if not exist Framework\ exit 1
	cd Framework\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\ZZC\Desktop\Application\Framework\Framework.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-Framework-install_subtargets: FORCE
	@if not exist Framework\ mkdir Framework\ & if not exist Framework\ exit 1
	cd Framework\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\ZZC\Desktop\Application\Framework\Framework.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-Framework-uninstall_subtargets: FORCE
	@if not exist Framework\ mkdir Framework\ & if not exist Framework\ exit 1
	cd Framework\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\ZZC\Desktop\Application\Framework\Framework.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-app-qmake_all:  FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && $(QMAKE) -o Makefile C:\Users\ZZC\Desktop\Application\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd app\ && $(MAKE) -f Makefile qmake_all
sub-app: FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\ZZC\Desktop\Application\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-app-make_first: FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\ZZC\Desktop\Application\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-app-all: FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\ZZC\Desktop\Application\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-app-clean: FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\ZZC\Desktop\Application\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-app-distclean: FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\ZZC\Desktop\Application\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-app-install_subtargets: FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\ZZC\Desktop\Application\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-app-uninstall_subtargets: FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\ZZC\Desktop\Application\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall

Makefile: Application.pro D:/Software/Qt/5.12.10/mingw73_64/mkspecs/win32-g++/qmake.conf D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/spec_pre.prf \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/qdevice.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/device_config.prf \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/common/sanitize.conf \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/common/gcc-base.conf \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/common/g++-base.conf \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/common/angle.conf \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/win32/windows_vulkan_sdk.prf \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/common/windows-vulkan.conf \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/common/g++-win32.conf \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/qconfig.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3danimation.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dcore.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dextras.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dinput.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dlogic.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dquick.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3drender.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3drender_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_axbase.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_axbase_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_axcontainer.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_axcontainer_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_axserver.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_axserver_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_bluetooth.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_charts.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_charts_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_concurrent.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_core.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_core_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_datavisualization.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_dbus.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_dbus_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_designer.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_designer_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_gamepad.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_gui.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_gui_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_help.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_help_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_location.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_location_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_multimedia.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_network.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_network_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_networkauth.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_nfc.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_nfc_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_opengl.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_opengl_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_openglextensions.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_positioning.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_positioning_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_positioningquick.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_printsupport.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_purchasing.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_qml.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_qml_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_qmltest.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_quick.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_quick_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_repparser.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_repparser_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_script.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_script_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_scripttools.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_scxml.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_scxml_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_sensors.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_sensors_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_serialbus.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_serialport.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_serialport_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_sql.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_sql_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_svg.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_svg_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_testlib.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_testlib_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_texttospeech.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_uiplugin.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_uitools.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_uitools_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_webchannel.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_websockets.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_websockets_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_widgets.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_widgets_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_winextras.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_winextras_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_xml.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_xml_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/qt_functions.prf \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/qt_config.prf \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/win32-g++/qmake.conf \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/exclusive_builds.prf \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/toolchain.prf \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/default_pre.prf \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/win32/default_pre.prf \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/resolve_config.prf \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/exclusive_builds_post.prf \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/default_post.prf \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/qml_debug.prf \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/precompile_header.prf \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/warn_on.prf \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/qmake_use.prf \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/file_copies.prf \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/win32/windows.prf \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/testcase_targets.prf \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/exceptions.prf \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/yacc.prf \
		D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/lex.prf \
		Application.pro
	$(QMAKE) -o Makefile Application.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/spec_pre.prf:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/qdevice.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/device_config.prf:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/common/sanitize.conf:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/common/gcc-base.conf:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/common/g++-base.conf:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/common/angle.conf:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/win32/windows_vulkan_sdk.prf:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/common/windows-vulkan.conf:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/common/g++-win32.conf:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/qconfig.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3danimation.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3danimation_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dcore.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dcore_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dextras.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dextras_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dinput.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dinput_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dlogic.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dquick.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dquick_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dquickextras.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dquickinput.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dquickrender.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3drender.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_3drender_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_axbase.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_axbase_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_axcontainer.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_axcontainer_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_axserver.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_axserver_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_bluetooth.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_charts.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_charts_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_concurrent.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_concurrent_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_core.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_core_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_datavisualization.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_dbus.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_dbus_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_designer.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_designer_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_edid_support_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_egl_support_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_fb_support_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_gamepad.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_gamepad_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_gui.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_gui_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_help.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_help_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_location.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_location_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_multimedia.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_multimedia_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_network.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_network_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_networkauth.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_networkauth_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_nfc.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_nfc_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_opengl.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_opengl_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_openglextensions.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_positioning.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_positioning_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_positioningquick.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_printsupport.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_printsupport_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_purchasing.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_purchasing_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_qml.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_qml_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_qmltest.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_qmltest_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_quick.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_quick_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_quickwidgets.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_remoteobjects.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_repparser.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_repparser_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_script.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_script_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_scripttools.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_scripttools_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_scxml.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_scxml_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_sensors.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_sensors_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_serialbus.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_serialbus_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_serialport.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_serialport_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_sql.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_sql_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_svg.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_svg_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_testlib.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_testlib_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_texttospeech.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_theme_support_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_uiplugin.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_uitools.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_uitools_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_vulkan_support_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_webchannel.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_webchannel_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_websockets.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_websockets_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_widgets.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_widgets_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_winextras.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_winextras_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_xml.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_xml_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/qt_functions.prf:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/qt_config.prf:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/win32-g++/qmake.conf:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/spec_post.prf:
.qmake.stash:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/exclusive_builds.prf:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/toolchain.prf:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/default_pre.prf:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/win32/default_pre.prf:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/resolve_config.prf:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/exclusive_builds_post.prf:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/default_post.prf:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/qml_debug.prf:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/precompile_header.prf:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/warn_on.prf:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/qmake_use.prf:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/file_copies.prf:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/win32/windows.prf:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/testcase_targets.prf:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/exceptions.prf:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/yacc.prf:
D:/Software/Qt/5.12.10/mingw73_64/mkspecs/features/lex.prf:
Application.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile Application.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: sub-Framework-qmake_all sub-app-qmake_all FORCE

make_first: sub-Framework-make_first sub-app-make_first  FORCE
all: sub-Framework-all sub-app-all  FORCE
clean: sub-Framework-clean sub-app-clean  FORCE
distclean: sub-Framework-distclean sub-app-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-Framework-install_subtargets sub-app-install_subtargets FORCE
uninstall_subtargets: sub-Framework-uninstall_subtargets sub-app-uninstall_subtargets FORCE

sub-Framework-debug:
	@if not exist Framework\ mkdir Framework\ & if not exist Framework\ exit 1
	cd Framework\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\ZZC\Desktop\Application\Framework\Framework.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-app-debug:
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\ZZC\Desktop\Application\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
debug: sub-Framework-debug sub-app-debug

sub-Framework-release:
	@if not exist Framework\ mkdir Framework\ & if not exist Framework\ exit 1
	cd Framework\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\ZZC\Desktop\Application\Framework\Framework.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-app-release:
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\ZZC\Desktop\Application\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
release: sub-Framework-release sub-app-release

sub-Framework-check:
	@if not exist Framework\ mkdir Framework\ & if not exist Framework\ exit 1
	cd Framework\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\ZZC\Desktop\Application\Framework\Framework.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-app-check:
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\ZZC\Desktop\Application\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
check: sub-Framework-check sub-app-check

sub-Framework-benchmark:
	@if not exist Framework\ mkdir Framework\ & if not exist Framework\ exit 1
	cd Framework\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\ZZC\Desktop\Application\Framework\Framework.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-app-benchmark:
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\ZZC\Desktop\Application\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-Framework-benchmark sub-app-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

