#ifndef VXMODULETYPEDEF_H
#define VXMODULETYPEDEF_H

typedef enum{
    MODULE_CONFIG_ID = 100000,
    MODULE_TIME_API,
    MODULE_TEST_PGM_ID,
    MODULE_TASKMANAGER,
    MODULE_MQTTSERVER,  //mqtt服务
    MODULE_MQTTTASK
}ENUM_XMODULE;
#endif // VXMODULETYPEDEF_H
